# Generated by Django 4.2.1 on 2023-09-02 15:38

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_date', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('min_count', models.IntegerField()),
                ('desc', models.TextField()),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_date', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_to)),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_date', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products')),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
