# Generated by Django 4.2.1 on 2023-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('min_count', models.IntegerField()),
                ('desc', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
